/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LogTrack;
import model.TipoUsuarioEnum;
import model.Usuarios;

/**
 *
 * @author felip
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private Usuarios usuarioLogado;
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        
        logout();
        usuarioLogado = new Usuarios();
    }
    private void login() {
        
        jTextFieldUsuario.setText(null);
        jPasswordFieldSenha.setText(null);
        jPanelLogin.setVisible(false);
        
        jMenuUsuario.setText( usuarioLogado.getNome() );
        jMenuUsuario.setVisible(true);
        
        jMenuAdministrativo.setVisible(true);
        jMenuFuncionario.setVisible(true);
        
        if (usuarioLogado.getTipoUsuario() == TipoUsuarioEnum.ADMINISTRADOR) {
            jMenuAdministrativo.setEnabled(true); 
        } else {
            jMenuAdministrativo.setEnabled(false);            // Desativa o menu administrativo      
        }
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     private void logout() {
        
        jPanelLogin.setVisible(true);
        
        jMenuUsuario.setText("Usuário");
        jMenuUsuario.setVisible(false);
        
        jMenuAdministrativo.setVisible(false);
        jMenuFuncionario.setVisible(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabelBemVindo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministrativo = new javax.swing.JMenu();
        jMenuItemConsultaCadastro = new javax.swing.JMenuItem();
        jMenuItemConsultaDoadores = new javax.swing.JMenuItem();
        jMenuConsultaDoacoes = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuItemConsultaAnimal = new javax.swing.JMenuItem();
        jMenuItemConsultaAdotantes = new javax.swing.JMenuItem();
        jMenuItemConsultaAdocoes = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Abrigo de Animais");

        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuario.setText("ID Usuário:");

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jLabelSenha.setText("Senha:");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jPasswordFieldSenha)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(16, 16, 16))
        );

        jLabelBemVindo.setText("Bem vindo!");

        jMenuAdministrativo.setText("Administrativo");
        jMenuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdministrativoActionPerformed(evt);
            }
        });

        jMenuItemConsultaCadastro.setText("Consulta Cadastro Usuario");
        jMenuItemConsultaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaCadastroActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaCadastro);

        jMenuItemConsultaDoadores.setText("Consulta Doadores");
        jMenuItemConsultaDoadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDoadoresActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaDoadores);

        jMenuConsultaDoacoes.setText("Consulta Doações");
        jMenuConsultaDoacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaDoacoesActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuConsultaDoacoes);

        jMenuBar1.add(jMenuAdministrativo);

        jMenuFuncionario.setText("Funcionario");

        jMenuItemConsultaAnimal.setText("Consulta Cadastro Animal");
        jMenuItemConsultaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAnimalActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemConsultaAnimal);

        jMenuItemConsultaAdotantes.setText("Consulta Adotantes");
        jMenuItemConsultaAdotantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAdotantesActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemConsultaAdotantes);

        jMenuItemConsultaAdocoes.setText("Consulta Adoções");
        jMenuItemConsultaAdocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAdocoesActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemConsultaAdocoes);

        jMenuBar1.add(jMenuFuncionario);

        jMenuUsuario.setText("Usuário");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemSair);

        jMenuBar1.add(jMenuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabelBemVindo)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelBemVindo)
                .addGap(18, 18, 18)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:  
        try {
            
            if( jTextFieldUsuario.getText().isEmpty() ||
                !jTextFieldUsuario.getText().matches("\\d+") ) {
            throw new Exception("Usuário Inválido! Usuario deve ser um numero!");
            }
            
            int id = Integer.parseInt( jTextFieldUsuario.getText() );
            
            usuarioLogado.setId(id);
            usuarioLogado.load(); // hash do banco de dados
            
            Usuarios usuarios = new Usuarios(); 
            usuarios.setId( id );
            usuarios.setSenha( jPasswordFieldSenha.getText() ); // hash da senha informada
            
            if( usuarioLogado.getSenha().equals( usuarios.getSenha() ) ) {
                login();
            } else {
                usuarioLogado = new Usuarios();
                throw new Exception("Senha Inválida!");
            }
            
                        
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            
            if( jTextFieldUsuario.getText().isEmpty() ||
                    !jTextFieldUsuario.getText().matches("\\d+") ) {
                throw new Exception("Usuário Inválido!");
            }
            
            int id = Integer.parseInt( jTextFieldUsuario.getText() );
            
            usuarioLogado.setId(id);
            usuarioLogado.load(); // hash do banco de dados
            
            Usuarios usuarios = new Usuarios(); 
            usuarios.setId( id );
            usuarios.setSenha( jPasswordFieldSenha.getText() ); // hash da senha informada
            
            if( usuarioLogado.getSenha().equals( usuarios.getSenha() ) ) {
                login();
            } else {
                usuarioLogado = new Usuarios();
                throw new Exception("Senha Inválida!");
            }
            
                        
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdministrativoActionPerformed
        // TODO add your handling code here:
         try {
            
            JFrameUsuariosConsulta jFrame;
            jFrame = new JFrameUsuariosConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuAdministrativoActionPerformed

    private void jMenuItemConsultaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaCadastroActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameUsuariosConsulta jFrame;
            jFrame = new JFrameUsuariosConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuItemConsultaCadastroActionPerformed

    private void jMenuItemConsultaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAnimalActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameAnimaisConsulta jFrame;
            jFrame = new JFrameAnimaisConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuItemConsultaAnimalActionPerformed

    private void jMenuConsultaDoacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaDoacoesActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameDoacoesConsulta jFrame;
            jFrame = new JFrameDoacoesConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuConsultaDoacoesActionPerformed

    private void jMenuItemConsultaAdotantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAdotantesActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameAdotantesConsulta jFrame;
            jFrame = new JFrameAdotantesConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuItemConsultaAdotantesActionPerformed

    private void jMenuItemConsultaAdocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAdocoesActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameAdocoesConsulta jFrame;
            jFrame = new JFrameAdocoesConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuItemConsultaAdocoesActionPerformed

    private void jMenuItemConsultaDoadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDoadoresActionPerformed
        // TODO add your handling code here:
        try {
            
            JFrameDoadoresConsulta jFrame;
            jFrame = new JFrameDoadoresConsulta( null, true, false );
            jFrame.setVisible(true);
            
        } catch( Exception ex ) {
            LogTrack.getInstance().adicionarLog(ex, true, this);
        }
    }//GEN-LAST:event_jMenuItemConsultaDoadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAdministrativo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultaDoacoes;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItemConsultaAdocoes;
    private javax.swing.JMenuItem jMenuItemConsultaAdotantes;
    private javax.swing.JMenuItem jMenuItemConsultaAnimal;
    private javax.swing.JMenuItem jMenuItemConsultaCadastro;
    private javax.swing.JMenuItem jMenuItemConsultaDoadores;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
